default: &default
  adapter: postgresql
  encoding: unicode
  # host: postgres
  # username: postgres
  # password:
  pool: 5

development:
  <<: *default
  database: Envoice_client_development

test:
  <<: *default
  database: Envoice_client_test

production:
  <<: *default
  database: Envoice_client_production
